call CleanTests.bat
call RunUnitTests.bat
call RunWaveCompareTests.bat
call RunWaveConvertTests.bat
call RunWaveEchoTests.bat
call RunWaveEQTests.bat
call RunWaveExtendTests.bat
call RunWaveFadeTests.bat
call RunWaveGateTests.bat
call RunWaveInfoTests.bat
call RunWaveJoinTests.bat
call RunWaveMixTests.bat
call RunWaveNormalizeTests.bat
call RunWavePrintTests.bat
call RunWaveRateTests.bat
call RunWaveStretchTests.bat
call RunWaveTremoloTests.bat
call RunWaveTrimTests.bat
call RunWaveVibratoTests.bat
call RunWaveVolumeTests.bat
